### PR TITLE
[DO NOT MERGE] Try latest master with boost 1.86

### PR DESCRIPTION
**Pull request by traversaro**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
Unfortunatly even the latest version fails with serialization related errors:

~~~
12/21 Test #12: test_planner_data ................***Failed  115.96 sec
Running 6 test cases...
Error:   Failed to load PlannerData: input stream error
         at line 147 in $SRC_DIR/src/ompl/base/src/PlannerDataStorage.cpp
$SRC_DIR/tests/base/planner_data.cpp:530: error: in "Serialization": check data2.numVertices() == states.size() has failed [0 != 1000]
$SRC_DIR/tests/base/planner_data.cpp:531: error: in "Serialization": check data2.numEdges() == num_edges_to_add has failed [0 != 10000]
$SRC_DIR/tests/base/planner_data.cpp:534: error: in "Serialization": check data2.numStartVertices() == 3 has failed
$SRC_DIR/tests/base/planner_data.cpp:535: error: in "Serialization": check data2.numGoalVertices() == 2 has failed
$SRC_DIR/tests/base/planner_data.cpp:536: error: in "Serialization": check data2.isStartVertex(0) has failed
$SRC_DIR/tests/base/planner_data.cpp:537: error: in "Serialization": check data2.isStartVertex(states.size()/2) has failed
$SRC_DIR/tests/base/planner_data.cpp:538: error: in "Serialization": check data2.isStartVertex(states.size()-1) has failed
$SRC_DIR/tests/base/planner_data.cpp:539: error: in "Serialization": check data2.isGoalVertex(1) has failed
$SRC_DIR/tests/base/planner_data.cpp:540: error: in "Serialization": check data2.isGoalVertex(states.size()-2) has failed
unknown location:0: fatal error: in "Serialization": memory access violation at address: 0x8: no mapping at fault address
$SRC_DIR/tests/base/planner_data.cpp:544: last checkpoint

*** 10 failures are detected in the test module "PlannerData"


      Start 13: test_ptc
13/21 Test #13: test_ptc .........................   Passed    0.26 sec
      Start 14: test_2dmap_geometric_simple
14/21 Test #14: test_2dmap_geometric_simple ......   Passed    0.28 sec
      Start 15: test_2dmap_ik
15/21 Test #15: test_2dmap_ik ....................   Passed    0.03 sec
      Start 16: test_2dcircles_opt_geometric
16/21 Test #16: test_2dcircles_opt_geometric .....   Passed   50.56 sec
      Start 17: test_2dpath_simplifying
17/21 Test #17: test_2dpath_simplifying ..........   Passed    0.14 sec
      Start 18: test_constraint_sphere
unknown location:0: fatal error: in "Serialization": memory access violation at address: 0x8: no mapping at fault address
$SRC_DIR/tests/control/planner_data.cpp:555: last checkpoint

*** 3 failures are detected in the test module "PlannerDataControl"

**Comment by Tobias-Fischer** [comment]
That’s bad news :(. I’ll try and find some time to look into it but don’t want to promise anything

**Comment by Tobias-Fischer** [comment]
@traversaro any chance to give this another go? There seem some fixes in https://github.com/ompl/ompl/pull/1188 which were not picked up here I think.

**Comment by traversaro** [comment]
> @traversaro any chance to give this another go? There seem some fixes in [ompl/ompl#1188](https://github.com/ompl/ompl/pull/1188) which were not picked up here I think.

Unfortunately in https://github.com/traversaro/ompl-macos-test I always test the latest master, and the problem is still there, xref https://github.com/conda-forge/ompl-feedstock/issues/43 .

**Comment by Tobias-Fischer** [comment]
I think I narrowed it down to: https://github.com/ompl/ompl/blob/1fae8db0a91a28af6087ad93790ec0232be96a11/src/ompl/base/PlannerDataStorage.h#L153 which is a raw pointer that is not correctly (de)serialized. But I don't understand enough of the boost serialization stuff to fix it ..

**Comment by traversaro** [comment]
> I think I narrowed it down to: https://github.com/ompl/ompl/blob/1fae8db0a91a28af6087ad93790ec0232be96a11/src/ompl/base/PlannerDataStorage.h#L153 which is a raw pointer that is not correctly (de)serialized. But I don't understand enough of the boost serialization stuff to fix it ..

Great catch!

**Comment by traversaro** [comment]
The problematic tests were skipped in https://github.com/conda-forge/ompl-feedstock/pull/47, the debug continues in https://github.com/conda-forge/ompl-feedstock/issues/43 .

**Pull request closed without merging**
