### PR TITLE
Rebuild to pull in New versions of dependencies

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Tackling https://github.com/johnwason/tesseract-robotics-superpack-feedstock/issues/9

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
This should pull in a new version of libode.

**Comment by Tobias-Fischer** [comment]
Cc @johnwason

**Comment by johnwason** [comment]
I think you might still need libode during runtime. ompl uses libode for collision checking (IIRC).

**Comment by Tobias-Fischer** [comment]
`libode` now has a correct run dependency on itself, so it will still be pulled in :) https://github.com/conda-forge/libode-feedstock/pull/13

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by wolfv** [comment]
Looks good to me! Ready to merge?!

**Comment by Tobias-Fischer** [comment]
Thanks for merging @wolfv! @johnwason - does that fix your issues?

**Comment by johnwason** [comment]
Yeah, this has fixed the issue

**Comment by johnwason** [comment]
Hmm now I am seeing a new issue building on Windows. I am not sure yet if this is being caused by tesseract or ompl: https://github.com/johnwason/tesseract-robotics-superpack-feedstock/runs/4056488382?check_suite_focus=true#step:6:3727

**Comment by wolfv** [comment]
Looks like there is a weird extra `:` instead of a `;`?

**Comment by johnwason** [comment]
@wolfv not sure where that is coming from since this worked with the previous ompl package version.

**Comment by wolfv** [comment]
hmm, there is at least one weirdness: (note the `:D:...` in the second include dir.

```
foreach(_dir D:/bld/ompl_1635583757784/_h_env/Library/include;:D:/bld/ompl_1635583757784/_h_env/Library/include;;TRIANGLE_INCLUDE_DIR-NOTFOUND;;;;)
    if(_dir)
        list(APPEND OMPL_INCLUDE_DIRS "${_dir}")
    endif()
endforeach()
```

**Comment by johnwason** [comment]
This is the source line for that input:

https://github.com/ompl/ompl/blob/d101202ebcb3fe9c7882c286615f00887e73e775/omplConfig.cmake.in#L23

That corresponds to `@ODE_INCLUDE_DIRS@`

This may be an problem in libode?

**Comment by wolfv** [comment]
Ok, so the OMPL CMake uses the `libode` pkgconfig file

```
prefix=D:/bld/libode_1633359337364/_h_env/Library
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include
precision=dDOUBLE

Name: ode
Description: Open Dynamics Engine
Version: 0.16.2
Libs: "/LIBPATH:${libdir}" ode_double.lib
# Libs.private: -lstdc++ -lm
Cflags: -I:${includedir}
```

The problem seems to be the `Cflags` that contains a `:` in the `-I:${...`.

I am not sure that is the true cause of your build problems, but it would be interesting to verify. We can patch libode to remove the extra colon.

**Comment by wolfv** [comment]
@johnwason I see the same in a previous build of OMPL 1.5.2 but __not__ in OMPL 1.4.2

Did 1.4.2 work for you?

**Comment by johnwason** [comment]
Yeah, 1.4.2 worked fine.

https://github.com/johnwason/tesseract-robotics-superpack-feedstock/actions/runs/1334751332

**Comment by wolfv** [comment]
Ok, then we've got to patch libode :)

**Comment by wolfv** [comment]
Looks like we're already patching libode, and are actually introducing this problem here: https://github.com/regro-cf-autotick-bot/libode-feedstock/blob/master/recipe/modify-dotpc-win

Will have a look for a fix tomorrow.

**Comment by wolfv** [comment]
@Tobias-Fischer shoudl we add the OMPL dependencies to the conda-forge pinnings so taht we get automatic migrations in the future?

**Comment by Tobias-Fischer** [comment]
Good idea @wolfv!

**Comment by johnwason** [comment]
I see the update https://github.com/conda-forge/libode-feedstock/pull/15 in libode, but the build is still failing. I think ompl needs to be rebuilt to pull in the libode updates.

**Comment by wolfv** [comment]
Yes, indeed. Do you want to send a pr incrementing the build number of ompl? :)

**Comment by johnwason** [comment]
@wolfv see https://github.com/conda-forge/ompl-feedstock/pull/13

**Comment by johnwason** [comment]
Still no luck on the windows build error:

https://github.com/johnwason/tesseract-robotics-superpack-feedstock/runs/4099598942?check_suite_focus=true#step:6:2730

**Comment by Tobias-Fischer** [comment]
It's still pulling in the old ompl (1.5.2-hbf27b1e_1). It takes some hours before the CDN syncs etc.; give it another go later :)

**Comment by johnwason** [comment]
All good now 👍

**Comment by wolfv** [comment]
Happy to hear that!

**Pull request merged**
