### PR TITLE
Bump version to 1.5.0 and fix automatic update PRs

### PR DESCRIPTION
**Pull request by Anthchirp**
Duplicate keys mean that only the latter URL is actually used. Duplicate
keys also mean that the conda-forge update detection bot will fail and
thus not automatically open PRs when upstream updates are available.

Bump version to 1.5.0

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by wolfv** [comment]
Are you interested in being a co-maintainer?

**Comment by Anthchirp** [comment]
> Are you interested in being a co-maintainer?

No thank you, I don't even know what to do about the failing tests here 🙃

**Pull request merged**
